In [58]:
import pandas as pd 
from pathlib import Path 
data_dir = Path('../data')
resume_dataset1=pd.read_csv(data_dir/'raw/resumes_dataset.csv')
resume_dataset2=pd.read_csv(data_dir/'raw/UpdatedResumeDataSet.csv')

In [59]:
## 1. RESUME DATASET

### Lecture et affichage des donnees

In [60]:
#Lecture et affichage Information dataframme
def read_data(data)->None:
    print("\n __Aperçu des données :")
    print(data.head(3))
    # Afficher les informations sur le DataFrame
    print("\n __Informations sur les données :")
    print(data.info())
    print(" \n __Taille : \n",data.shape)
    print("\n __Information sur les Categories: \n",data['Category'].value_counts().reset_index())

In [61]:
read_data(resume_dataset1)

 __Aperçu des données :
                        Category  \
0         Database Administrator
1         Database Administrator
2  Oracle Database Administrator

                                              Resume
0  Ability: Installation and Building Server, Run...
1  Ability: database management systems administr...
2  Ability: Over 4+ years of Experience as Archit...

 __Informations sur les données :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18798 entries, 0 to 18797
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  18798 non-null  object
 1   Resume    18798 non-null  object
dtypes: object(2)
memory usage: 293.8+ KB
None

 __Taille :
 (18798, 2)

 __Information sur les Categories:
                     Category  count
0      Network Administrator   1416
1           Python Developer   1092
2             Java Developer    948
3     Database Administrator    939
4        Front End Developer    864
..                       ...    ...
188  UI/ Front End Developer     21
189     Technical Consultant     21
190          Program Manager     21
191            Self Employed     21
192         PYTHON DEVELOPER     21

[193 rows x 2 columns]

In [62]:
read_data(resume_dataset2)

 __Aperçu des données :
       Category                                             Resume
0  Data Science  Skills * Programming Languages: Python (pandas...
1  Data Science  Education Details \r\nMay 2013 to May 2017 B.E...
2  Data Science  Areas of Interest Deep Learning, Control Syste...

 __Informations sur les données :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 962 entries, 0 to 961
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  962 non-null    object
 1   Resume    962 non-null    object
dtypes: object(2)
memory usage: 15.2+ KB
None

 __Taille :
 (962, 2)

 __Information sur les Categories:
                      Category  count
0              Java Developer     84
1                     Testing     70
2             DevOps Engineer     55
3            Python Developer     48
4               Web Designing     45
5                          HR     44
6                      Hadoop     42
7                  Blockchain     40
8               ETL Developer     40
9          Operations Manager     40
10               Data Science     40
11                      Sales     40
12        Mechanical Engineer     40
13                       Arts     36
14                   Database     33
15     Electrical Engineering     30
16         Health and fitness     30
17                        PMO     30
18           Business Analyst     28
19           DotNet Developer     28
20         Automation Testing     26
21  Network Security Engineer     25
22              SAP Developer     24
23             Civil Engineer     24
24                   Advocate     20

##### Suppression des lignes avec categories Biasees  dataset1

In [63]:
# Liste des catégories à supprimer / recuperer en amont pendant la reuperation du dataset
categories_a_supprimer = [
    'Troy', 'Robert Half', 'Edison', 'Unknown','Chandler','Irving','Laurel','Charles Schwab'
]
# Filtrer pour garder seulement les lignes NON dans cette liste
new_resume_dataset1 = resume_dataset1[~resume_dataset1['Category'].isin(categories_a_supprimer)]
read_data(new_resume_dataset1)

 __Aperçu des données :
                        Category  \
0         Database Administrator
1         Database Administrator
2  Oracle Database Administrator

                                              Resume
0  Ability: Installation and Building Server, Run...
1  Ability: database management systems administr...
2  Ability: Over 4+ years of Experience as Archit...

 __Informations sur les données :
<class 'pandas.core.frame.DataFrame'>
Index: 18570 entries, 0 to 18797
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  18570 non-null  object
 1   Resume    18570 non-null  object
dtypes: object(2)
memory usage: 435.2+ KB
None

 __Taille :
 (18570, 2)

 __Information sur les Categories:
                      Category  count
0       Network Administrator   1416
1            Python Developer   1092
2              Java Developer    948
3      Database Administrator    939
4         Front End Developer    864
..                        ...    ...
180      Technical Consultant     21
181     Data Security Analyst     21
182             Self Employed     21
183  Salesforce Administrator     21
184          PYTHON DEVELOPER     21

[185 rows x 2 columns]

#### Verification Valeur manquante et chaine vide des dataset

In [64]:
from numpy import empty


def missing_values(data1,data2=empty )->None:
    #Verification Valeur manquante
    print("\n  Dataseset1:")
    print(" \t Valeur manquante  ::")
    print(data1.isna().sum())
    print("\n Chaine vide:")
    print("Resume",data1['Resume'].apply(lambda x: str(x).strip() == '').sum())
    print("Category",data1['Category'].apply(lambda x: str(x).strip() == '').sum())
    
    if data2 is not empty :
        print(" \n \t -------------------------------:: \n ")
        print("  Dataseset2:")
        print(" \t Valeur manquante  ::")
        print(data2.isna().sum())
        print(" \t \t Chaine vide   ::")
        print("Resume",data2['Resume'].apply(lambda x: str(x).strip() == '').sum())
        print("Category",data2['Category'].apply(lambda x: str(x).strip() == '').sum())
    else:
        print(" \n ")

In [65]:
missing_values(new_resume_dataset1,resume_dataset2)

  Dataseset1:
 	 Valeur manquante  ::
Category    0
Resume      0
dtype: int64

 Chaine vide:
Resume 0
Category 0

 	 -------------------------------::

  Dataseset2:
 	 Valeur manquante  ::
Category    0
Resume      0
dtype: int64
 	 	 Chaine vide   ::
Resume 0
Category 0

### Combinaison des 2 dataset :resumes_dataset et UpdateResume

In [66]:
combined_resume_dataset = pd.concat([new_resume_dataset1, resume_dataset2], axis=0, ignore_index=True)
# Vérification
print(f"Taille dataset1: {len(new_resume_dataset1)} lignes")
print(f"Taille dataset2: {len(resume_dataset2)} lignes")
print(f"Taille combinée: {len(combined_resume_dataset)} lignes")
print("\n Aperçu du résultat:")
print(combined_resume_dataset.head(3))

Taille dataset1: 18570 lignes
Taille dataset2: 962 lignes
Taille combinée: 19532 lignes

 Aperçu du résultat:
                        Category  \
0         Database Administrator
1         Database Administrator
2  Oracle Database Administrator

                                              Resume
0  Ability: Installation and Building Server, Run...
1  Ability: database management systems administr...
2  Ability: Over 4+ years of Experience as Archit...

#### Verification Valeur manquante et chaine vide des dataset

In [67]:
missing_values(combined_resume_dataset)

  Dataseset1:
 	 Valeur manquante  ::
Category    0
Resume      0
dtype: int64

 Chaine vide:
Resume 0
Category 0

In [68]:
read_data(combined_resume_dataset)

 __Aperçu des données :
                        Category  \
0         Database Administrator
1         Database Administrator
2  Oracle Database Administrator

                                              Resume
0  Ability: Installation and Building Server, Run...
1  Ability: database management systems administr...
2  Ability: Over 4+ years of Experience as Archit...

 __Informations sur les données :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19532 entries, 0 to 19531
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  19532 non-null  object
 1   Resume    19532 non-null  object
dtypes: object(2)
memory usage: 305.3+ KB
None

 __Taille :
 (19532, 2)

 __Information sur les Categories:
                     Category  count
0      Network Administrator   1416
1           Python Developer   1140
2             Java Developer   1032
3     Database Administrator    939
4        Front End Developer    864
..                       ...    ...
200    Sr. Software Engineer     21
201    Data Security Analyst     21
202  Freelance Web Developer     21
203         PYTHON DEVELOPER     21
204                 Advocate     20

[205 rows x 2 columns]

#### Suppresssion des doublons

In [69]:
combined_resume_dataset = combined_resume_dataset.drop_duplicates()
read_data(combined_resume_dataset)

 __Aperçu des données :
                        Category  \
0         Database Administrator
1         Database Administrator
2  Oracle Database Administrator

                                              Resume
0  Ability: Installation and Building Server, Run...
1  Ability: database management systems administr...
2  Ability: Over 4+ years of Experience as Archit...

 __Informations sur les données :
<class 'pandas.core.frame.DataFrame'>
Index: 6346 entries, 0 to 19468
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  6346 non-null   object
 1   Resume    6346 non-null   object
dtypes: object(2)
memory usage: 148.7+ KB
None

 __Taille :
 (6346, 2)

 __Information sur les Categories:
                    Category  count
0     Network Administrator    472
1          Python Developer    368
2            Java Developer    329
3    Database Administrator    312
4       Front End Developer    288
..                      ...    ...
200     Mechanical Engineer      5
201           ETL Developer      5
202              Blockchain      5
203           Web Designing      4
204                     PMO      3

[205 rows x 2 columns]

### Combinaison DATASET FINAL

#### Ajout 3eme dataset resume_dataset_JitWah

In [70]:
resume_dataset3=pd.read_csv(data_dir/'raw/combined_resume_dataset_JitWah.csv')
read_data(resume_dataset3)

 __Aperçu des données :
                 Category                                             Resume
0  Database_Administrator  Database Administrator Database Administrator ...
1  Database_Administrator  Consultant Consultant Consultant - Infosys Tec...
2  Database_Administrator  Corporate Buying Data Assistant Corporate Buyi...

 __Informations sur les données :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5758 entries, 0 to 5757
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5758 non-null   object
 1   Resume    5758 non-null   object
dtypes: object(2)
memory usage: 90.1+ KB
None

 __Taille :
 (5758, 2)

 __Information sur les Categories:
                                Category  count
0                      Security_Analyst    861
1                    Software_Developer    783
2      Web_Developer,Software_Developer    648
3                 Network_Administrator    556
4   Python_Developer,Software_Developer    521
5                       Project_manager    438
6                 Systems_Administrator    419
7      Software_Developer,Web_Developer    413
8     Java_Developer,Software_Developer    388
9                Database_Administrator    319
10   Project_manager,Software_Developer    242
11                 Full Stack Developer     30
12                       Data Scientist     29
13                   Frontend Developer     24
14   Mobile App Developer (iOS/Android)     23
15                       Cloud Engineer     23
16                     Python Developer     22
17                    Backend Developer     19

#### Combinaison des dataset :resume_dataset3 et combined_resume_dataset

In [71]:
combined_resume_dataset_final = pd.concat([combined_resume_dataset, resume_dataset3], axis=0, ignore_index=True)

# Vérification
print(f"Taille dataset1c: {len(combined_resume_dataset)} lignes")
print(f"Taille dataset3: {len(resume_dataset3)} lignes")
print(f"Taille combinée final: {len(combined_resume_dataset_final)} lignes")
read_data(combined_resume_dataset_final)

Taille dataset1c: 6346 lignes
Taille dataset3: 5758 lignes
Taille combinée final: 12104 lignes

 __Aperçu des données :
                        Category  \
0         Database Administrator
1         Database Administrator
2  Oracle Database Administrator

                                              Resume
0  Ability: Installation and Building Server, Run...
1  Ability: database management systems administr...
2  Ability: Over 4+ years of Experience as Archit...

 __Informations sur les données :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12104 entries, 0 to 12103
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  12104 non-null  object
 1   Resume    12104 non-null  object
dtypes: object(2)
memory usage: 189.2+ KB
None

 __Taille :
 (12104, 2)

 __Information sur les Categories:
                                 Category  count
0                       Security_Analyst    861
1                     Software_Developer    783
2       Web_Developer,Software_Developer    648
3                  Network_Administrator    556
4    Python_Developer,Software_Developer    521
..                                   ...    ...
215                        ETL Developer      5
216               Electrical Engineering      5
217                  Mechanical Engineer      5
218                        Web Designing      4
219                                  PMO      3

[220 rows x 2 columns]

#### Suppresssion des doublons

In [72]:
combined_resume_dataset_final = combined_resume_dataset_final.drop_duplicates()
read_data(combined_resume_dataset_final)

 __Aperçu des données :
                        Category  \
0         Database Administrator
1         Database Administrator
2  Oracle Database Administrator

                                              Resume
0  Ability: Installation and Building Server, Run...
1  Ability: database management systems administr...
2  Ability: Over 4+ years of Experience as Archit...

 __Informations sur les données :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12104 entries, 0 to 12103
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  12104 non-null  object
 1   Resume    12104 non-null  object
dtypes: object(2)
memory usage: 189.2+ KB
None

 __Taille :
 (12104, 2)

 __Information sur les Categories:
                                 Category  count
0                       Security_Analyst    861
1                     Software_Developer    783
2       Web_Developer,Software_Developer    648
3                  Network_Administrator    556
4    Python_Developer,Software_Developer    521
..                                   ...    ...
215                        ETL Developer      5
216               Electrical Engineering      5
217                  Mechanical Engineer      5
218                        Web Designing      4
219                                  PMO      3

[220 rows x 2 columns]

In [73]:
missing_values(combined_resume_dataset_final)

  Dataseset1:
 	 Valeur manquante  ::
Category    0
Resume      0
dtype: int64

 Chaine vide:
Resume 0
Category 0

#### Enregistrement dataset

In [74]:
# new_resume_dataset1.to_csv(data_dir/'interim/resumes_clean_Category.csv', index=False)
combined_resume_dataset_final.to_csv(data_dir/'interim/combined_resume_final.csv', index=False)

## 2. Job Offer DATASET

In [75]:
offer_dataset1=pd.read_csv(data_dir/'raw/new_job_description.csv')
offer_dataset2=pd.read_csv(data_dir/'raw/Cleaned_DS_Jobs.csv')

In [76]:
offer_dataset1.head()

,Job Title_Category,Job Description
0,Prompt Engineer and Librarian,"Anthropic’s mission is to create reliable, int..."
1,Social Sciences Librarian - 500421,Social Sciences Librarian - 500421\n\nSUMMARY:...
2,"Collection Management Specialist, EBSCO Books",EBSCO Information Services (EIS) provides a co...
3,Humanities Librarian,SUMMARY:\nThe Humanities Librarian serves as t...
4,Librarian,"Salary Range\n\n$49,705 - $95,595/annually\nWo..."

In [77]:
offer_dataset2.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,company_age,python,excel,hadoop,spark,aws,tableau,big_data,job_simp,seniority
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,Nonprofit Organization,Insurance Carriers,...,27,0,0,0,0,1,0,0,data scientist,senior
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,Company - Public,Research & Development,...,52,0,0,1,0,0,0,1,data scientist,na
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,Private Practice / Firm,Consulting,...,39,1,1,0,0,1,0,0,data scientist,na
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,Company - Public,Electrical & Electronic Manufacturing,...,20,1,1,0,0,1,0,0,data scientist,na
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,Company - Private,Advertising & Marketing,...,22,1,1,0,0,0,0,0,data scientist,na

#### Suppression colonnes

In [78]:
columns_to_drop=['Rating','Headquarters','Location','Company Name','Size',
                 'Type of ownership','Salary Estimate','Industry','python','excel',
                'hadoop','spark','aws','tableau','big_data','job_simp','seniority',
                'Sector','Revenue','min_salary','max_salary','avg_salary','job_state','same_state','company_age']


offer_dataset2=offer_dataset2.drop(columns=columns_to_drop)
offer_dataset2=offer_dataset2.rename(columns={'Job Title':'Job Title_Category'})
offer_dataset2.head()

  Job Title_Category                                    Job Description
0  Sr Data Scientist  Description\n\nThe Senior Data Scientist is re...
1     Data Scientist  Secure our Nation, Ignite your Future\n\nJoin ...
2     Data Scientist  Overview\n\n\nAnalysis Group is one of the lar...
3     Data Scientist  JOB DESCRIPTION:\n\nDo you have a passion for ...
4     Data Scientist  Data Scientist\nAffinity Solutions / Marketing...

#### Verification Valeur manquante

In [79]:

print("\n  Dataseset1:")
print(" \t Valeur manquante  ::")
print(offer_dataset1.isna().sum())
print("\n Chaine vide:")
print("Job Description",offer_dataset1['Job Description'].apply(lambda x: str(x).strip() == '').sum())
print("Job Title_Category",offer_dataset1['Job Title_Category'].apply(lambda x: str(x).strip() == '').sum())
print(" \n \t -------------------------------:: \n ")
print("  Dataseset2:")
print(" \t Valeur manquante  ::")
print(offer_dataset2.isna().sum())
print(" \t \t Chaine vide   ::")
print("Job Description",offer_dataset2['Job Description'].apply(lambda x: str(x).strip() == '').sum())
print("Job Title_Category",offer_dataset2['Job Title_Category'].apply(lambda x: str(x).strip() == '').sum())

  Dataseset1:
 	 Valeur manquante  ::
Job Title_Category    0
Job Description       0
dtype: int64

 Chaine vide:
Job Description 0
Job Title_Category 0

 	 -------------------------------::

  Dataseset2:
 	 Valeur manquante  ::
Job Title_Category    0
Job Description       0
dtype: int64
 	 	 Chaine vide   ::
Job Description 0
Job Title_Category 0

### Combinaison des DATASET

In [80]:
combined_offer_dataset = pd.concat([offer_dataset1, offer_dataset2], axis=0, ignore_index=True)
combined_offer_dataset =combined_offer_dataset.drop_duplicates()
combined_offer_dataset =combined_offer_dataset.dropna()
# Vérification
print(f"Taille dataset1: {len(offer_dataset1)} lignes")
print(f"Taille dataset2: {len(offer_dataset2)} lignes")
print(f"Taille combinée: {len(combined_offer_dataset)} lignes")
print("\n Aperçu du résultat:")
print(combined_offer_dataset.head(3))

Taille dataset1: 2856 lignes
Taille dataset2: 660 lignes
Taille combinée: 3339 lignes

 Aperçu du résultat:
                              Job Title_Category  \
0                  Prompt Engineer and Librarian
1             Social Sciences Librarian - 500421
2  Collection Management Specialist, EBSCO Books

                                     Job Description
0  Anthropic’s mission is to create reliable, int...
1  Social Sciences Librarian - 500421\n\nSUMMARY:...
2  EBSCO Information Services (EIS) provides a co...

In [81]:
combined_offer_dataset.to_csv(data_dir/'interim/combined_offer_dataset.csv', index=False)