In [42]:
import pandas as pd 
from pathlib import Path 
data_dir = Path('../data')
resume_dataset1=pd.read_csv(data_dir/'raw/resumes_dataset.csv')
resume_dataset2=pd.read_csv(data_dir/'raw/UpdatedResumeDataSet.csv')

### Lecture et affichage des donnees

In [43]:
resume_dataset1.head()

,Category,Resume
0,Database Administrator,"Ability: Installation and Building Server, Run..."
1,Database Administrator,Ability: database management systems administr...
2,Oracle Database Administrator,Ability: Over 4+ years of Experience as Archit...
3,Oracle Database Administrator,"Ability: Oracle Database Administration, Datab..."
4,Oracle Database Administrator,"Ability: Oracle Database Administration, Oracl..."

In [44]:
resume_dataset2.head()

       Category                                             Resume
0  Data Science  Skills * Programming Languages: Python (pandas...
1  Data Science  Education Details \r\nMay 2013 to May 2017 B.E...
2  Data Science  Areas of Interest Deep Learning, Control Syste...
3  Data Science  Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
4  Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...

In [45]:
#Lecture et affichage Information dataframme
def read_data(data):
    print("\n __Aperçu des données :")
    print(data.head(3))
    # Afficher les informations sur le DataFrame
    print("\n __Informations sur les données :")
    print(data.info())
    print(" \n __Taille : \n",data.shape)
    print("\n __Information sur les Categories: \n",data['Category'].value_counts().reset_index())

In [46]:
read_data(resume_dataset1)

 __Aperçu des données :
                        Category  \
0         Database Administrator
1         Database Administrator
2  Oracle Database Administrator

                                              Resume
0  Ability: Installation and Building Server, Run...
1  Ability: database management systems administr...
2  Ability: Over 4+ years of Experience as Archit...

 __Informations sur les données :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18798 entries, 0 to 18797
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  18798 non-null  object
 1   Resume    18798 non-null  object
dtypes: object(2)
memory usage: 293.8+ KB
None

 __Taille :
 (18798, 2)

 __Information sur les Categories:
                     Category  count
0      Network Administrator   1416
1           Python Developer   1092
2             Java Developer    948
3     Database Administrator    939
4        Front End Developer    864
..                       ...    ...
188  UI/ Front End Developer     21
189     Technical Consultant     21
190          Program Manager     21
191            Self Employed     21
192         PYTHON DEVELOPER     21

[193 rows x 2 columns]

In [47]:
read_data(resume_dataset2)

 __Aperçu des données :
       Category                                             Resume
0  Data Science  Skills * Programming Languages: Python (pandas...
1  Data Science  Education Details \r\nMay 2013 to May 2017 B.E...
2  Data Science  Areas of Interest Deep Learning, Control Syste...

 __Informations sur les données :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 962 entries, 0 to 961
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  962 non-null    object
 1   Resume    962 non-null    object
dtypes: object(2)
memory usage: 15.2+ KB
None

 __Taille :
 (962, 2)

 __Information sur les Categories:
                      Category  count
0              Java Developer     84
1                     Testing     70
2             DevOps Engineer     55
3            Python Developer     48
4               Web Designing     45
5                          HR     44
6                      Hadoop     42
7                  Blockchain     40
8               ETL Developer     40
9          Operations Manager     40
10               Data Science     40
11                      Sales     40
12        Mechanical Engineer     40
13                       Arts     36
14                   Database     33
15     Electrical Engineering     30
16         Health and fitness     30
17                        PMO     30
18           Business Analyst     28
19           DotNet Developer     28
20         Automation Testing     26
21  Network Security Engineer     25
22              SAP Developer     24
23             Civil Engineer     24
24                   Advocate     20

##### Suppression des lignes avec categories Biasees  dataset1

In [48]:
# Liste des catégories à supprimer / recuperer en amont pendant la reuperation du dataset
categories_a_supprimer = [
    'Troy', 'Robert Half', 'Edison', 'Unknown','Chandler','Irving','Laurel','Charles Schwab'
]
# Filtrer pour garder seulement les lignes NON dans cette liste
new_resume_dataset1 = resume_dataset1[~resume_dataset1['Category'].isin(categories_a_supprimer)]
read_data(new_resume_dataset1)

 __Aperçu des données :
                        Category  \
0         Database Administrator
1         Database Administrator
2  Oracle Database Administrator

                                              Resume
0  Ability: Installation and Building Server, Run...
1  Ability: database management systems administr...
2  Ability: Over 4+ years of Experience as Archit...

 __Informations sur les données :
<class 'pandas.core.frame.DataFrame'>
Index: 18570 entries, 0 to 18797
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  18570 non-null  object
 1   Resume    18570 non-null  object
dtypes: object(2)
memory usage: 435.2+ KB
None

 __Taille :
 (18570, 2)

 __Information sur les Categories:
                      Category  count
0       Network Administrator   1416
1            Python Developer   1092
2              Java Developer    948
3      Database Administrator    939
4         Front End Developer    864
..                        ...    ...
180      Technical Consultant     21
181     Data Security Analyst     21
182             Self Employed     21
183  Salesforce Administrator     21
184          PYTHON DEVELOPER     21

[185 rows x 2 columns]

#### Verification Valeur manquante#####  et chaine vide dataset

In [49]:
#Verification Valeur manquante
print(" \t Valeur manquante  ::")
print("\n _Dataset1:")
print(new_resume_dataset1.isna().sum())
print("\n Dataset2:")
print(resume_dataset2.isna().sum())

 	 Valeur manquante  ::

 _Dataset1:
Category    0
Resume      0
dtype: int64

 Dataset2:
Category    0
Resume      0
dtype: int64

In [50]:
#Verification chaine vide dataset
print(" \t \t Chaine vide   ::")
print("  Dataseset1:")

print("Resume",resume_dataset2['Resume'].apply(lambda x: str(x).strip() == '').sum())
print("Category",resume_dataset2['Category'].apply(lambda x: str(x).strip() == '').sum())
print("\n  Dataseset1:")
print("Resume",new_resume_dataset1['Resume'].apply(lambda x: str(x).strip() == '').sum())
print("Category",new_resume_dataset1['Category'].apply(lambda x: str(x).strip() == '').sum())

 	 	 Chaine vide   ::
  Dataseset1:
Resume 0
Category 0

  Dataseset1:
Resume 0
Category 0

### Concactenation 2 dataset :resumes_dataset et UpdateResume

In [58]:
combined_resume_dataset = pd.concat([new_resume_dataset1, resume_dataset2], axis=0, ignore_index=True)

# Vérification
print(f"Taille dataset1: {len(new_resume_dataset1)} lignes")
print(f"Taille dataset2: {len(resume_dataset2)} lignes")
print(f"Taille combinée: {len(combined_resume_dataset)} lignes")
print("\n Aperçu du résultat:")
print(combined_resume_dataset.head())

Taille dataset1: 6180 lignes
Taille dataset2: 166 lignes
Taille combinée: 6346 lignes

 Aperçu du résultat:
                        Category  \
0         Database Administrator
1         Database Administrator
2  Oracle Database Administrator
3  Oracle Database Administrator
4  Oracle Database Administrator

                                              Resume
0  Ability: Installation and Building Server, Run...
1  Ability: database management systems administr...
2  Ability: Over 4+ years of Experience as Archit...
3  Ability: Oracle Database Administration, Datab...
4  Ability: Oracle Database Administration, Oracl...

In [59]:
print(" \t \t Chaine vide   ::")
print("  Dataseset1:")

print("Resume",combined_resume_dataset['Resume'].apply(lambda x: str(x).strip() == '').sum())
print("Category",combined_resume_dataset['Category'].apply(lambda x: str(x).strip() == '').sum())

 	 	 Chaine vide   ::
  Dataseset1:
Resume 0
Category 0

In [60]:
print(" \t Valeur manquante  ::")
print("\n _Dataset1:")
print(combined_resume_dataset.isna().sum())
print("\n Dataset2:")
print(combined_resume_dataset.isna().sum())

 	 Valeur manquante  ::

 _Dataset1:
Category    0
Resume      0
dtype: int64

 Dataset2:
Category    0
Resume      0
dtype: int64

In [61]:
read_data(combined_resume_dataset)

 __Aperçu des données :
                        Category  \
0         Database Administrator
1         Database Administrator
2  Oracle Database Administrator

                                              Resume
0  Ability: Installation and Building Server, Run...
1  Ability: database management systems administr...
2  Ability: Over 4+ years of Experience as Archit...

 __Informations sur les données :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6346 entries, 0 to 6345
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  6346 non-null   object
 1   Resume    6346 non-null   object
dtypes: object(2)
memory usage: 99.3+ KB
None

 __Taille :
 (6346, 2)

 __Information sur les Categories:
                    Category  count
0     Network Administrator    472
1          Python Developer    368
2            Java Developer    329
3    Database Administrator    312
4       Front End Developer    288
..                      ...    ...
200     Mechanical Engineer      5
201           ETL Developer      5
202              Blockchain      5
203           Web Designing      4
204                     PMO      3

[205 rows x 2 columns]

####Suppresssion des doublons

In [62]:
combined_resume_dataset = combined_resume_dataset.drop_duplicates()
read_data(combined_resume_dataset)

 __Aperçu des données :
                        Category  \
0         Database Administrator
1         Database Administrator
2  Oracle Database Administrator

                                              Resume
0  Ability: Installation and Building Server, Run...
1  Ability: database management systems administr...
2  Ability: Over 4+ years of Experience as Archit...

 __Informations sur les données :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6346 entries, 0 to 6345
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  6346 non-null   object
 1   Resume    6346 non-null   object
dtypes: object(2)
memory usage: 99.3+ KB
None

 __Taille :
 (6346, 2)

 __Information sur les Categories:
                    Category  count
0     Network Administrator    472
1          Python Developer    368
2            Java Developer    329
3    Database Administrator    312
4       Front End Developer    288
..                      ...    ...
200     Mechanical Engineer      5
201           ETL Developer      5
202              Blockchain      5
203           Web Designing      4
204                     PMO      3

[205 rows x 2 columns]

In [64]:
# new_resume_dataset1 = new_resume_dataset1.drop_duplicates()
# read_data(new_resume_dataset1)
# resume_dataset2 = resume_dataset2.drop_duplicates()
# read_data(resume_dataset2)

### Ajout 3eme dataset

In [71]:
resume_dataset3=pd.read_csv(data_dir/'raw/combined_resume_dataset_JitWah.csv')
read_data(resume_dataset3)

 __Aperçu des données :
                 Category                                             Resume
0  Database_Administrator  Database Administrator Database Administrator ...
1  Database_Administrator  Consultant Consultant Consultant - Infosys Tec...
2  Database_Administrator  Corporate Buying Data Assistant Corporate Buyi...

 __Informations sur les données :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5758 entries, 0 to 5757
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5758 non-null   object
 1   Resume    5758 non-null   object
dtypes: object(2)
memory usage: 90.1+ KB
None

 __Taille :
 (5758, 2)

 __Information sur les Categories:
                                Category  count
0                      Security_Analyst    861
1                    Software_Developer    783
2      Web_Developer,Software_Developer    648
3                 Network_Administrator    556
4   Python_Developer,Software_Developer    521
5                       Project_manager    438
6                 Systems_Administrator    419
7      Software_Developer,Web_Developer    413
8     Java_Developer,Software_Developer    388
9                Database_Administrator    319
10   Project_manager,Software_Developer    242
11                 Full Stack Developer     30
12                       Data Scientist     29
13                   Frontend Developer     24
14   Mobile App Developer (iOS/Android)     23
15                       Cloud Engineer     23
16                     Python Developer     22
17                    Backend Developer     19

### DATASET FINAL

In [78]:
combined_resume_dataset_final = pd.concat([combined_resume_dataset, resume_dataset3], axis=0, ignore_index=True)

# Vérification
print(f"Taille dataset1c: {len(combined_resume_dataset)} lignes")
print(f"Taille dataset3: {len(resume_dataset3)} lignes")
print(f"Taille combinée final: {len(combined_resume_dataset_final)} lignes")
read_data(combined_resume_dataset_final)

Taille dataset1c: 6346 lignes
Taille dataset3: 5758 lignes
Taille combinée final: 12104 lignes

 __Aperçu des données :
                        Category  \
0         Database Administrator
1         Database Administrator
2  Oracle Database Administrator

                                              Resume
0  Ability: Installation and Building Server, Run...
1  Ability: database management systems administr...
2  Ability: Over 4+ years of Experience as Archit...

 __Informations sur les données :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12104 entries, 0 to 12103
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  12104 non-null  object
 1   Resume    12104 non-null  object
dtypes: object(2)
memory usage: 189.2+ KB
None

 __Taille :
 (12104, 2)

 __Information sur les Categories:
                                 Category  count
0                       Security_Analyst    861
1                     Software_Developer    783
2       Web_Developer,Software_Developer    648
3                  Network_Administrator    556
4    Python_Developer,Software_Developer    521
..                                   ...    ...
215                        ETL Developer      5
216               Electrical Engineering      5
217                  Mechanical Engineer      5
218                        Web Designing      4
219                                  PMO      3

[220 rows x 2 columns]

In [79]:
combined_resume_dataset_final = combined_resume_dataset_final.drop_duplicates()
read_data(combined_resume_dataset_final)

 __Aperçu des données :
                        Category  \
0         Database Administrator
1         Database Administrator
2  Oracle Database Administrator

                                              Resume
0  Ability: Installation and Building Server, Run...
1  Ability: database management systems administr...
2  Ability: Over 4+ years of Experience as Archit...

 __Informations sur les données :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12104 entries, 0 to 12103
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  12104 non-null  object
 1   Resume    12104 non-null  object
dtypes: object(2)
memory usage: 189.2+ KB
None

 __Taille :
 (12104, 2)

 __Information sur les Categories:
                                 Category  count
0                       Security_Analyst    861
1                     Software_Developer    783
2       Web_Developer,Software_Developer    648
3                  Network_Administrator    556
4    Python_Developer,Software_Developer    521
..                                   ...    ...
215                        ETL Developer      5
216               Electrical Engineering      5
217                  Mechanical Engineer      5
218                        Web Designing      4
219                                  PMO      3

[220 rows x 2 columns]

In [80]:
print(" \t \t Chaine vide   ::")
print("  Dataseset:")

print("Resume",combined_resume_dataset_final['Resume'].apply(lambda x: str(x).strip() == '').sum())
print("Category",combined_resume_dataset_final['Category'].apply(lambda x: str(x).strip() == '').sum())
print(" \t \t Valeur manquante  ::")
print("\n _Dataset1:")
print(combined_resume_dataset_final.isna().sum())

 	 	 Chaine vide   ::
  Dataseset:
Resume 0
Category 0
 	 	 Valeur manquante  ::

 _Dataset1:
Category    0
Resume      0
dtype: int64

#### Enregistrement dataset

In [81]:
new_resume_dataset1.to_csv(data_dir/'interim/resumes_clean_Category.csv', index=False)
combined_resume_dataset_final.to_csv(data_dir/'interim/combined_resume_final.csv', index=False)